### ISSUE TITLE
writing never throws an error

### ISSUE THREAD

**Issue by corzand** [don/mifare-classic-js#2]
based on example write.js:

when i do:

sudo node write.js 

and i don't have a tag in range, the writing never fails and always returns "OK".

**Comment by don** [comment]
It's annoying that there's no feedback from write. This would be a great feature to add! This package is just a light wrapper (or hack) around mifare-classic-read-ndef and mifare-classic-write-ndef to demonstrate https://github.com/don/ndef-js.

**Comment by don** [comment]
It looks like this fork added some waiting https://github.com/KungAlex/mifare-classic-js, which might be the same code as #4. (I'm nit sure why the author closed that pull request.)
