### ISSUE TITLE
Implement a getUID of the mifare classic card function

### ISSUE THREAD

**Issue by zanechua** [don/mifare-classic-js#3]
Hey Don,

I was looking for this function but realised it isn't included.

```
function getUid(data)
{
    var uid = data.slice(33, 41);
    return uid;
}
```

I wrote some code based on the data received from the read function and passed the buffer data over to this method to return the uid.

**Comment by don** [comment]
https://github.com/don/mifare-classic-js/commit/b2d07bfded0b581df6cdfaa7a870bf12dcc067a9 parses the uid and returns to the callback

**Comment by zanechua** [comment]
Awesome. Thanks @don for fixing it. Even though I don't use it anymore. I'm sure someone will find it useful!
